name: NPM Publish Workflow
on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release version to publish (e.g., 1.0.0)'
        required: true
      branch:
        description: 'Branch/tag to publish from'
        required: true
        default: 'main'
  workflow_call:
    inputs:
      release-version:
        description: 'Release version to publish'
        required: true
        type: string
      branch:
        description: 'Branch/tag to publish from'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Apitomy'
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          ref: ${{ inputs.branch }}

      - name: Setup Node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: 22.23.2
          registry-url: 'https://registry.npmjs.org'


      - name: Log Metadata
        run: |
          echo "Publishing Apitomy Flow UI version ${{ inputs.release-version }} to npm"
          echo "Publishing from branch/tag: ${{ inputs.branch }}"


      - name: Build Project
        run: |
          npm ci
          npm run lint
          npm run build
        working-directory: ui


      - name: Publish to npm
        run: npm publish --provenance --access public
        working-directory: ui
        env:
          NODE_AUTH_TOKEN: ''


      - name: Slack Notification (Always)
        if: always()
        run: |
          MESSAGE="NPM publish for version ${{ inputs.release-version }} completed with status: ${{ job.status }}"
          REPO="${{ github.repository }}"
          LINK="https://github.com/$REPO/actions/runs/${{ github.run_id }}"
          PAYLOAD="{\"workflow\": \"${{ github.workflow }}\", \"status\": \"${{ job.status }}\", \"message\": \"$MESSAGE\", \"link\": \"$LINK\", \"repository\": \"$REPO\"}"
          curl -X POST -H "Content-Type: application/json" -d "$PAYLOAD" ${{ secrets.SLACK_NOTIFICATION_WEBHOOK }}

      - name: Slack Notification (Error)
        if: failure()
        run: |
          MESSAGE="NPM publish for version ${{ inputs.release-version }} FAILED!"
          REPO="${{ github.repository }}"
          LINK="https://github.com/$REPO/actions/runs/${{ github.run_id }}"
          PAYLOAD="{\"workflow\": \"${{ github.workflow }}\", \"status\": \"${{ job.status }}\", \"message\": \"$MESSAGE\", \"link\": \"$LINK\", \"repository\": \"$REPO\"}"
          curl -X POST -H "Content-Type: application/json" -d "$PAYLOAD" ${{ secrets.SLACK_ERROR_WEBHOOK }}
